### ISSUE TITLE
Lode image link should be HTTPs encrypted

### ISSUE THREAD

**Issue by derekbelrose** [rmap-project/rmap-ontology#2]
The favicon is linked to http://eelst.cs.unibo.it/apps/LODE/favicon.ico but new browser policies warn users that this site could be dangerous because it's not HTTPs encrypted. 

Is it possible for us to store the favicon locally or get an HTTPs link from Bologna?

**Comment by htpvu** [comment]
I think the best way to do this is the use a different favicon for this actually. I'll lookfor/create an RMap favicon which we can store locally.

**Comment by derekbelrose** [comment]
I am ok with this.  Thank you for into it :)

**Comment by htpvu** [comment]
Added RMap favicon, updated the html file to use it. Fix in commit 439b68c
